export type ExpensePageKind = 'company' | 'business-unit' | 'project';

export type ExpenseStatus = 'Paid' | 'Under Process' | 'Pending Approval' | 'Overdue' | 'Cancelled';

export interface DemoExpense {
  id: string;
  expenseNumber: string;
  date: string;
  scopeLabel: string;
  businessUnit?: string;
  project?: string;
  category: string;
  subCategory: string;
  vendor: string;
  basicAmount: number;
  gstAmount: number;
  totalAmount: number;
  paidAmount: number;
  pendingAmount: number;
  status: ExpenseStatus;
  remarks: string;
}

export interface ExpenseDataset {
  kind: ExpensePageKind;
  title: string;
  description: string;
  scopeColumnLabel: string;
  formScopeLabel: string;
  rows: DemoExpense[];
}

export const expenseStatuses: ExpenseStatus[] = [
  'Paid',
  'Under Process',
  'Pending Approval',
  'Overdue',
  'Cancelled',
];

export const expenseSubCategories: Record<string, string[]> = {
  Office: ['Rent', 'Security Deposit', 'Electricity Charges', 'Maintenance', 'Printing & Stationery', 'Legal & Notary Charges', 'Tour & Travel', 'Admin', 'Misc', 'Staff Salary', 'Banking Charges', 'IT Assets'],
  Compliance: ['CA Fees', 'Taxes & Duties', 'Project Insurance', 'Labour License', 'Registration Expenses', 'Consultancy Charges'],
  'Guest House': ['Rent', 'Maintenance', 'Care Taker Salary', 'Guest House Admin Expenses'],
  Tender: ['EMD', 'Cost of Tender Document'],
  Vehicle: ['Vehicle EMI', 'Vehicle Diesel', 'Vehicle Fuel'],
  'Plant & Machinery': ['Equipment EMI', 'Equipment- Diesel', 'Equipment- Insurance', 'Equipment- Maintenance', 'Equipment- Spares', 'Equipment- Transporation', 'Spares- Transporation', 'Equipment - Purchase', 'Equipment - Downpayment'],
  Material: ['Supply', 'Primary Transportation', 'Secondary Transportation'],
  Services: ['Vendor Payment', 'Right of Way Payment', 'Labour Charges', 'Site Expenses'],
  Warehouse: ['Rent', 'Security Deposit', 'Electricity Charges', 'Maintenance', 'Printing & Stationery', 'Establishment', 'Security', 'IT Assets', 'Labour Charges Loading-Unloading'],
  Finance: ['Finance Charges'],
};

export const expenseCategories = Object.keys(expenseSubCategories);

export const businessUnits = ['Telecom', 'Gas Pipelines', 'Sewerage', 'Railways'];

export const projectNames = ['Bharat Net', 'GAIL', 'BGCL', 'NFS', 'STP'];

export const companyExpenseRows: DemoExpense[] = [
  {
    id: 'cmp-001',
    expenseNumber: 'CEXP-2026-001',
    date: '2026-04-02',
    scopeLabel: 'Corporate Office',
    category: 'Office',
    subCategory: 'Rent',
    vendor: 'Metro Business Centre',
    basicAmount: 1280000,
    gstAmount: 230400,
    totalAmount: 1510400,
    paidAmount: 1510400,
    pendingAmount: 0,
    status: 'Paid',
    remarks: 'Monthly corporate office rent and facility charges.',
  },
  {
    id: 'cmp-002',
    expenseNumber: 'CEXP-2026-002',
    date: '2026-04-05',
    scopeLabel: 'Finance Shared Services',
    category: 'Finance',
    subCategory: 'Finance Charges',
    vendor: 'Axis Banking Services',
    basicAmount: 385000,
    gstAmount: 69300,
    totalAmount: 454300,
    paidAmount: 200000,
    pendingAmount: 254300,
    status: 'Under Process',
    remarks: 'Bank charges and guarantee processing fees.',
  },
  {
    id: 'cmp-003',
    expenseNumber: 'CEXP-2026-003',
    date: '2026-04-08',
    scopeLabel: 'Legal & Compliance',
    category: 'Compliance',
    subCategory: 'Registration Expenses',
    vendor: 'Rao & Mehta Associates',
    basicAmount: 640000,
    gstAmount: 115200,
    totalAmount: 755200,
    paidAmount: 0,
    pendingAmount: 755200,
    status: 'Pending Approval',
    remarks: 'Quarterly statutory filings and advisory retainer.',
  },
  {
    id: 'cmp-004',
    expenseNumber: 'CEXP-2026-004',
    date: '2026-04-12',
    scopeLabel: 'IT Administration',
    category: 'Office',
    subCategory: 'IT Assets',
    vendor: 'CloudDesk Technologies',
    basicAmount: 960000,
    gstAmount: 172800,
    totalAmount: 1132800,
    paidAmount: 1132800,
    pendingAmount: 0,
    status: 'Paid',
    remarks: 'Annual collaboration software and helpdesk licenses.',
  },
  {
    id: 'cmp-005',
    expenseNumber: 'CEXP-2026-005',
    date: '2026-04-16',
    scopeLabel: 'Corporate Office',
    category: 'Office',
    subCategory: 'Tour & Travel',
    vendor: 'Swift Travel Desk',
    basicAmount: 275000,
    gstAmount: 49500,
    totalAmount: 324500,
    paidAmount: 120000,
    pendingAmount: 204500,
    status: 'Overdue',
    remarks: 'Executive site review travel bookings.',
  },
  {
    id: 'cmp-006',
    expenseNumber: 'CEXP-2026-006',
    date: '2026-04-20',
    scopeLabel: 'Procurement',
    category: 'Office',
    subCategory: 'Printing & Stationery',
    vendor: 'Prime Stationers',
    basicAmount: 118000,
    gstAmount: 21240,
    totalAmount: 139240,
    paidAmount: 0,
    pendingAmount: 139240,
    status: 'Under Process',
    remarks: 'Stationery and printer consumables for shared departments.',
  },
  {
    id: 'cmp-007',
    expenseNumber: 'CEXP-2026-007',
    date: '2026-04-24',
    scopeLabel: 'Legal & Compliance',
    category: 'Compliance',
    subCategory: 'Taxes & Duties',
    vendor: 'Govt. Filing Portal',
    basicAmount: 82000,
    gstAmount: 0,
    totalAmount: 82000,
    paidAmount: 0,
    pendingAmount: 0,
    status: 'Cancelled',
    remarks: 'Duplicate filing entry cancelled before approval.',
  },
  {
    id: 'cmp-008',
    expenseNumber: 'CEXP-2026-008',
    date: '2026-05-01',
    scopeLabel: 'Finance Shared Services',
    category: 'Finance',
    subCategory: 'Finance Charges',
    vendor: 'AuditFirst LLP',
    basicAmount: 520000,
    gstAmount: 93600,
    totalAmount: 613600,
    paidAmount: 0,
    pendingAmount: 613600,
    status: 'Pending Approval',
    remarks: 'Internal audit support for annual closure.',
  },
];

export const businessUnitExpenseRows: DemoExpense[] = [
  {
    id: 'bu-001',
    expenseNumber: 'BUEXP-2026-001',
    date: '2026-04-01',
    scopeLabel: 'Telecom',
    businessUnit: 'Telecom',
    category: 'Services',
    subCategory: 'Right of Way Payment',
    vendor: 'Fiberline Services',
    basicAmount: 2480000,
    gstAmount: 446400,
    totalAmount: 2926400,
    paidAmount: 1900000,
    pendingAmount: 1026400,
    status: 'Under Process',
    remarks: 'Field coordination and route validation services.',
  },
  {
    id: 'bu-002',
    expenseNumber: 'BUEXP-2026-002',
    date: '2026-04-06',
    scopeLabel: 'Gas Pipelines',
    businessUnit: 'Gas Pipelines',
    category: 'Vehicle',
    subCategory: 'Vehicle Fuel',
    vendor: 'FleetWay Logistics',
    basicAmount: 875000,
    gstAmount: 157500,
    totalAmount: 1032500,
    paidAmount: 1032500,
    pendingAmount: 0,
    status: 'Paid',
    remarks: 'Inspection vehicle rentals and fuel support.',
  },
  {
    id: 'bu-003',
    expenseNumber: 'BUEXP-2026-003',
    date: '2026-04-11',
    scopeLabel: 'Sewerage',
    businessUnit: 'Sewerage',
    category: 'Warehouse',
    subCategory: 'Rent',
    vendor: 'Eastern Storage Park',
    basicAmount: 430000,
    gstAmount: 77400,
    totalAmount: 507400,
    paidAmount: 0,
    pendingAmount: 507400,
    status: 'Pending Approval',
    remarks: 'Temporary storage for pipes and fittings.',
  },
  {
    id: 'bu-004',
    expenseNumber: 'BUEXP-2026-004',
    date: '2026-04-14',
    scopeLabel: 'Railways',
    businessUnit: 'Railways',
    category: 'Compliance',
    subCategory: 'Project Insurance',
    vendor: 'SafetyCert India',
    basicAmount: 335000,
    gstAmount: 60300,
    totalAmount: 395300,
    paidAmount: 180000,
    pendingAmount: 215300,
    status: 'Overdue',
    remarks: 'Safety certification and documentation charges.',
  },
  {
    id: 'bu-005',
    expenseNumber: 'BUEXP-2026-005',
    date: '2026-04-18',
    scopeLabel: 'Telecom',
    businessUnit: 'Telecom',
    category: 'Material',
    subCategory: 'Supply',
    vendor: 'Network Infra Mart',
    basicAmount: 1720000,
    gstAmount: 309600,
    totalAmount: 2029600,
    paidAmount: 2029600,
    pendingAmount: 0,
    status: 'Paid',
    remarks: 'Cable trays, clamps, and passive components.',
  },
  {
    id: 'bu-006',
    expenseNumber: 'BUEXP-2026-006',
    date: '2026-04-22',
    scopeLabel: 'Gas Pipelines',
    businessUnit: 'Gas Pipelines',
    category: 'Plant & Machinery',
    subCategory: 'Equipment EMI',
    vendor: 'MachPro Rentals',
    basicAmount: 1380000,
    gstAmount: 248400,
    totalAmount: 1628400,
    paidAmount: 0,
    pendingAmount: 1628400,
    status: 'Under Process',
    remarks: 'Hydro testing equipment rental.',
  },
  {
    id: 'bu-007',
    expenseNumber: 'BUEXP-2026-007',
    date: '2026-04-27',
    scopeLabel: 'Sewerage',
    businessUnit: 'Sewerage',
    category: 'Services',
    subCategory: 'Site Expenses',
    vendor: 'Civic Works Agency',
    basicAmount: 690000,
    gstAmount: 124200,
    totalAmount: 814200,
    paidAmount: 0,
    pendingAmount: 814200,
    status: 'Pending Approval',
    remarks: 'Municipal coordination and site access support.',
  },
  {
    id: 'bu-008',
    expenseNumber: 'BUEXP-2026-008',
    date: '2026-05-03',
    scopeLabel: 'Railways',
    businessUnit: 'Railways',
    category: 'Office',
    subCategory: 'Tour & Travel',
    vendor: 'Trackline Hospitality',
    basicAmount: 214000,
    gstAmount: 38520,
    totalAmount: 252520,
    paidAmount: 0,
    pendingAmount: 0,
    status: 'Cancelled',
    remarks: 'Cancelled duplicate booking for inspection team.',
  },
];

export const projectExpenseRows: DemoExpense[] = [
  {
    id: 'prj-001',
    expenseNumber: 'PEXP-2026-001',
    date: '2026-04-03',
    scopeLabel: 'Bharat Net',
    businessUnit: 'Telecom',
    project: 'Bharat Net',
    category: 'Material',
    subCategory: 'Supply',
    vendor: 'FiberGrid Supplies',
    basicAmount: 3120000,
    gstAmount: 561600,
    totalAmount: 3681600,
    paidAmount: 2200000,
    pendingAmount: 1481600,
    status: 'Under Process',
    remarks: 'Optical fiber cable and accessories for block rollout.',
  },
  {
    id: 'prj-002',
    expenseNumber: 'PEXP-2026-002',
    date: '2026-04-07',
    scopeLabel: 'GAIL',
    businessUnit: 'Gas Pipelines',
    project: 'GAIL',
    category: 'Plant & Machinery',
    subCategory: 'Equipment - Purchase',
    vendor: 'PipeTech Equipment',
    basicAmount: 2450000,
    gstAmount: 441000,
    totalAmount: 2891000,
    paidAmount: 2891000,
    pendingAmount: 0,
    status: 'Paid',
    remarks: 'Pipe bending and alignment equipment mobilization.',
  },
  {
    id: 'prj-003',
    expenseNumber: 'PEXP-2026-003',
    date: '2026-04-10',
    scopeLabel: 'BGCL',
    businessUnit: 'Gas Pipelines',
    project: 'BGCL',
    category: 'Services',
    subCategory: 'Vendor Payment',
    vendor: 'SurveyPoint Consultants',
    basicAmount: 760000,
    gstAmount: 136800,
    totalAmount: 896800,
    paidAmount: 0,
    pendingAmount: 896800,
    status: 'Pending Approval',
    remarks: 'Route survey and land coordination.',
  },
  {
    id: 'prj-004',
    expenseNumber: 'PEXP-2026-004',
    date: '2026-04-15',
    scopeLabel: 'NFS',
    businessUnit: 'Telecom',
    project: 'NFS',
    category: 'Warehouse',
    subCategory: 'Rent',
    vendor: 'North East Warehousing',
    basicAmount: 580000,
    gstAmount: 104400,
    totalAmount: 684400,
    paidAmount: 300000,
    pendingAmount: 384400,
    status: 'Overdue',
    remarks: 'Regional warehouse rent for project materials.',
  },
  {
    id: 'prj-005',
    expenseNumber: 'PEXP-2026-005',
    date: '2026-04-19',
    scopeLabel: 'STP',
    businessUnit: 'Sewerage',
    project: 'STP',
    category: 'Services',
    subCategory: 'Labour Charges',
    vendor: 'Urban Civil Works',
    basicAmount: 1320000,
    gstAmount: 237600,
    totalAmount: 1557600,
    paidAmount: 1557600,
    pendingAmount: 0,
    status: 'Paid',
    remarks: 'Civil support for treatment plant milestone.',
  },
  {
    id: 'prj-006',
    expenseNumber: 'PEXP-2026-006',
    date: '2026-04-23',
    scopeLabel: 'Bharat Net',
    businessUnit: 'Telecom',
    project: 'Bharat Net',
    category: 'Vehicle',
    subCategory: 'Vehicle Diesel',
    vendor: 'Rural Fleet Services',
    basicAmount: 410000,
    gstAmount: 73800,
    totalAmount: 483800,
    paidAmount: 0,
    pendingAmount: 483800,
    status: 'Under Process',
    remarks: 'Village cluster team vehicle deployment.',
  },
  {
    id: 'prj-007',
    expenseNumber: 'PEXP-2026-007',
    date: '2026-04-28',
    scopeLabel: 'NFS',
    businessUnit: 'Telecom',
    project: 'NFS',
    category: 'Compliance',
    subCategory: 'Labour License',
    vendor: 'SecureAccess Labs',
    basicAmount: 225000,
    gstAmount: 40500,
    totalAmount: 265500,
    paidAmount: 0,
    pendingAmount: 265500,
    status: 'Pending Approval',
    remarks: 'Security clearance documentation for restricted zone work.',
  },
  {
    id: 'prj-008',
    expenseNumber: 'PEXP-2026-008',
    date: '2026-05-02',
    scopeLabel: 'GAIL',
    businessUnit: 'Gas Pipelines',
    project: 'GAIL',
    category: 'Office',
    subCategory: 'Tour & Travel',
    vendor: 'Pipeline Travel Desk',
    basicAmount: 146000,
    gstAmount: 26280,
    totalAmount: 172280,
    paidAmount: 0,
    pendingAmount: 0,
    status: 'Cancelled',
    remarks: 'Cancelled travel request after inspection reschedule.',
  },
];

export const expenseDatasets: Record<ExpensePageKind, ExpenseDataset> = {
  company: {
    kind: 'company',
    title: 'Company Expenses',
    description: 'Company-wide overheads, shared services, statutory costs, and administrative spend.',
    scopeColumnLabel: 'Cost Centre',
    formScopeLabel: 'Cost Centre',
    rows: companyExpenseRows,
  },
  'business-unit': {
    kind: 'business-unit',
    title: 'Business Unit Expenses',
    description: 'Operating expenses grouped by business unit across active divisions.',
    scopeColumnLabel: 'Business Unit',
    formScopeLabel: 'Business Unit',
    rows: businessUnitExpenseRows,
  },
  project: {
    kind: 'project',
    title: 'Project Expenses',
    description: 'Project-specific expense entries mapped to active contracts and execution teams.',
    scopeColumnLabel: 'Project',
    formScopeLabel: 'Project',
    rows: projectExpenseRows,
  },
};
